# Generated by Django 4.0.2 on 2022-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('other_titles', models.CharField(max_length=64)),
                ('connect', models.CharField(max_length=64)),
                ('add_time', models.CharField(max_length=64)),
                ('user', models.JSONField()),
                ('coords', models.JSONField()),
                ('type', models.CharField(default='pass', max_length=64)),
                ('level', models.JSONField()),
                ('images', models.JSONField()),
                ('status', models.CharField(default='new', max_length=16)),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('blob', models.BinaryField()),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
    ]
