# Generated by Django 4.0.2 on 2022-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(null=True)),
                ('images', models.JSONField(null=True)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('img', models.BinaryField()),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
    ]
