# Generated by Django 4.0.2 on 2022-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='connect',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
