# Generated by Django 4.0.2 on 2022-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='images',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='raw_data',
            field=models.JSONField(),
        ),
    ]
